name: mod-build
channels:
  - conda-forge
dependencies:
  - python=3.11
  - coincbc
  - pip
  - pip:
      - ipython
      - jupyter
      - numpy
      - matplotlib
      - pandas
      - scipy
      - casadi
      - pyyaml
      - pytest
      - modelon-impact-client